trigger:
- master
stages:
- stage: Build
  jobs:
  - job: Build	
    pool:
      vmImage: $(vmImageName)
    steps:
    - bash: pwd 
    - bash: ls -l 
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: '$(imageRepository)/$(name)'
        dockerfile: .
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/'
        ArtifactName: 'charts'
        publishLocation: 'Container'

    - task: Docker@2
      displayName: Push an image to container registry
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)